.TH "STM32L4xx_System_Private_Defines" 3 "ME_507_Lab2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
STM32L4xx_System_Private_Defines \- STM32L4xx_System_Private_Defines
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHSE_VALUE\fP   8000000U"
.br
.ti -1c
.RI "#define \fBMSI_VALUE\fP   4000000U"
.br
.ti -1c
.RI "#define \fBHSI_VALUE\fP   16000000U"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define HSE_VALUE   8000000U"
Value of the External oscillator in Hz 
.SS "#define HSI_VALUE   16000000U"
Value of the Internal oscillator in Hz 
.SS "#define MSI_VALUE   4000000U"
Value of the Internal oscillator in Hz 
.SH "Author"
.PP 
Generated automatically by Doxygen for ME_507_Lab2 from the source code\&.
